name = "rubber_pink_mastodon-bdf3"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "rubber_pink_mastodon-bdf3-debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "rubber_pink_mastodon-bdf3-release.wasm"
command = "npm run build:release"
